# Generated by Django 3.1.7 on 2021-04-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('quality', models.IntegerField(verbose_name=720)),
                ('name', models.CharField(max_length=20)),
                ('isReady', models.BooleanField(verbose_name='false')),
            ],
        ),
    ]
