# Generated by Django 3.2.1 on 2021-05-12 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RemoteControl', '0003_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user_id',
        ),
        migrations.AddField(
            model_name='device',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='isReady',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='quality',
            field=models.IntegerField(),
        ),
    ]
